package com.utah.frame.entity;

/**
 * 转码错误信息表
 */
public class ConvertError {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   机构id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.org_id
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     * Database Column Remarks:
     *   机构编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.org_code
     *
     * @mbg.generated
     */
    private String orgCode;

    /**
     * Database Column Remarks:
     *   机构名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.org_name
     *
     * @mbg.generated
     */
    private String orgName;

    /**
     * Database Column Remarks:
     *   任务id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.job_id
     *
     * @mbg.generated
     */
    private String jobId;

    /**
     * Database Column Remarks:
     *   文件id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.file_id
     *
     * @mbg.generated
     */
    private String fileId;

    /**
     * Database Column Remarks:
     *   文件名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.file_name
     *
     * @mbg.generated
     */
    private String fileName;

    /**
     * Database Column Remarks:
     *   服务器文件相对路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.file_url
     *
     * @mbg.generated
     */
    private String fileUrl;

    /**
     * Database Column Remarks:
     *   知识类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.kng_type
     *
     * @mbg.generated
     */
    private String kngType;

    /**
     * Database Column Remarks:
     *   视频分辨率：1080p、720p、480p、360p
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.resolution
     *
     * @mbg.generated
     */
    private String resolution;

    /**
     * Database Column Remarks:
     *   是否预览视频：0-普通视频, 1-预览视频
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.preview
     *
     * @mbg.generated
     */
    private Integer preview;

    /**
     * Database Column Remarks:
     *   是否H5专用视频：0-普通视频, 1-H5专用视频
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.h5
     *
     * @mbg.generated
     */
    private Integer h5;

    /**
     * Database Column Remarks:
     *   1-已加密, 0-未加密
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.enc
     *
     * @mbg.generated
     */
    private Integer enc;

    /**
     * Database Column Remarks:
     *   转码状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.convert_status
     *
     * @mbg.generated
     */
    private Integer convertStatus;

    /**
     * Database Column Remarks:
     *   错误信息描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.error_desp
     *
     * @mbg.generated
     */
    private String errorDesp;

    /**
     * Database Column Remarks:
     *   处理状态 0 待处理 1 处理中 2 处理完成 3 处理失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.deal_status
     *
     * @mbg.generated
     */
    private Integer dealStatus;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     * Database Column Remarks:
     *   处理备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column core_convert_error.remark
     *
     * @mbg.generated
     */
    private String remark;


}