package com.utah.frame.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Database Table Remarks:
 *   结算行扩展字段
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table intg_settlement_line_metadata
 */
public class IntgProjectLineMetadata {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   结算行idid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.line_id
     *
     * @mbg.generated
     */
    private String lineId;

    /**
     * Database Column Remarks:
     *   公司id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     * Database Column Remarks:
     *   租户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     * Database Column Remarks:
     *   扩展字段key值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.ext_key
     *
     * @mbg.generated
     */
    private String extKey;

    /**
     * Database Column Remarks:
     *   使用类型,custom 自定义类型、system 系统类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.usage
     *
     * @mbg.generated
     */
    private String usage;

    /**
     * Database Column Remarks:
     *   string类型扩展字段值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.string_value
     *
     * @mbg.generated
     */
    private String stringValue;

    /**
     * Database Column Remarks:
     *   decimal类型扩展字段值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.decimal_value
     *
     * @mbg.generated
     */
    private BigDecimal decimalValue;

    /**
     * Database Column Remarks:
     *   date类型扩展字段值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.date_value
     *
     * @mbg.generated
     */
    private Date dateValue;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * Database Column Remarks:
     *   是否删除;0-未删除，1-已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.is_deleted
     *
     * @mbg.generated
     */
    private Long isDeleted;

    /**
     * Database Column Remarks:
     *   乐观锁版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_settlement_line_metadata.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.id
     *
     * @return the value of intg_settlement_line_metadata.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.id
     *
     * @param id the value for intg_settlement_line_metadata.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.line_id
     *
     * @return the value of intg_settlement_line_metadata.line_id
     *
     * @mbg.generated
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.line_id
     *
     * @param lineId the value for intg_settlement_line_metadata.line_id
     *
     * @mbg.generated
     */
    public void setLineId(String lineId) {
        this.lineId = lineId == null ? null : lineId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.company_id
     *
     * @return the value of intg_settlement_line_metadata.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.company_id
     *
     * @param companyId the value for intg_settlement_line_metadata.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.tenant_id
     *
     * @return the value of intg_settlement_line_metadata.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.tenant_id
     *
     * @param tenantId the value for intg_settlement_line_metadata.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.ext_key
     *
     * @return the value of intg_settlement_line_metadata.ext_key
     *
     * @mbg.generated
     */
    public String getExtKey() {
        return extKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.ext_key
     *
     * @param extKey the value for intg_settlement_line_metadata.ext_key
     *
     * @mbg.generated
     */
    public void setExtKey(String extKey) {
        this.extKey = extKey == null ? null : extKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.usage
     *
     * @return the value of intg_settlement_line_metadata.usage
     *
     * @mbg.generated
     */
    public String getUsage() {
        return usage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.usage
     *
     * @param usage the value for intg_settlement_line_metadata.usage
     *
     * @mbg.generated
     */
    public void setUsage(String usage) {
        this.usage = usage == null ? null : usage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.string_value
     *
     * @return the value of intg_settlement_line_metadata.string_value
     *
     * @mbg.generated
     */
    public String getStringValue() {
        return stringValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.string_value
     *
     * @param stringValue the value for intg_settlement_line_metadata.string_value
     *
     * @mbg.generated
     */
    public void setStringValue(String stringValue) {
        this.stringValue = stringValue == null ? null : stringValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.decimal_value
     *
     * @return the value of intg_settlement_line_metadata.decimal_value
     *
     * @mbg.generated
     */
    public BigDecimal getDecimalValue() {
        return decimalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.decimal_value
     *
     * @param decimalValue the value for intg_settlement_line_metadata.decimal_value
     *
     * @mbg.generated
     */
    public void setDecimalValue(BigDecimal decimalValue) {
        this.decimalValue = decimalValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.date_value
     *
     * @return the value of intg_settlement_line_metadata.date_value
     *
     * @mbg.generated
     */
    public Date getDateValue() {
        return dateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.date_value
     *
     * @param dateValue the value for intg_settlement_line_metadata.date_value
     *
     * @mbg.generated
     */
    public void setDateValue(Date dateValue) {
        this.dateValue = dateValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.created_by
     *
     * @return the value of intg_settlement_line_metadata.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.created_by
     *
     * @param createdBy the value for intg_settlement_line_metadata.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.created_at
     *
     * @return the value of intg_settlement_line_metadata.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.created_at
     *
     * @param createdAt the value for intg_settlement_line_metadata.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.updated_by
     *
     * @return the value of intg_settlement_line_metadata.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.updated_by
     *
     * @param updatedBy the value for intg_settlement_line_metadata.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.updated_at
     *
     * @return the value of intg_settlement_line_metadata.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.updated_at
     *
     * @param updatedAt the value for intg_settlement_line_metadata.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.is_deleted
     *
     * @return the value of intg_settlement_line_metadata.is_deleted
     *
     * @mbg.generated
     */
    public Long getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.is_deleted
     *
     * @param isDeleted the value for intg_settlement_line_metadata.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Long isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_settlement_line_metadata.version
     *
     * @return the value of intg_settlement_line_metadata.version
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_settlement_line_metadata.version
     *
     * @param version the value for intg_settlement_line_metadata.version
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}