package com.utah.frame.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   ccp文件上传记录表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table intg_ccp_upload_record
 */
public class IntgCcpUploadRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   公司id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     * Database Column Remarks:
     *   租户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.tenant_id
     *
     * @mbg.generated
     */
    private String tenantId;

    /**
     * Database Column Remarks:
     *   原始上传文件名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.origin_filename
     *
     * @mbg.generated
     */
    private String originFilename;

    /**
     * Database Column Remarks:
     *   上传文件后缀名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.file_ext
     *
     * @mbg.generated
     */
    private String fileExt;

    /**
     * Database Column Remarks:
     *   文件上传大小(byte)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.file_size
     *
     * @mbg.generated
     */
    private Long fileSize;

    /**
     * Database Column Remarks:
     *   原始文件上传后存储路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.file_stored_path
     *
     * @mbg.generated
     */
    private String fileStoredPath;

    /**
     * Database Column Remarks:
     *   处理后下载存储路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.download_stored_path
     *
     * @mbg.generated
     */
    private String downloadStoredPath;

    /**
     * Database Column Remarks:
     *   处理状态,0 上传中、1 上传成功、2 上传失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.deal_status
     *
     * @mbg.generated
     */
    private Byte dealStatus;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     * Database Column Remarks:
     *   更新人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * Database Column Remarks:
     *   是否删除;0-未删除，1-已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.is_deleted
     *
     * @mbg.generated
     */
    private Long isDeleted;

    /**
     * Database Column Remarks:
     *   乐观锁版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intg_ccp_upload_record.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.id
     *
     * @return the value of intg_ccp_upload_record.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.id
     *
     * @param id the value for intg_ccp_upload_record.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.company_id
     *
     * @return the value of intg_ccp_upload_record.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.company_id
     *
     * @param companyId the value for intg_ccp_upload_record.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.tenant_id
     *
     * @return the value of intg_ccp_upload_record.tenant_id
     *
     * @mbg.generated
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.tenant_id
     *
     * @param tenantId the value for intg_ccp_upload_record.tenant_id
     *
     * @mbg.generated
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.origin_filename
     *
     * @return the value of intg_ccp_upload_record.origin_filename
     *
     * @mbg.generated
     */
    public String getOriginFilename() {
        return originFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.origin_filename
     *
     * @param originFilename the value for intg_ccp_upload_record.origin_filename
     *
     * @mbg.generated
     */
    public void setOriginFilename(String originFilename) {
        this.originFilename = originFilename == null ? null : originFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.file_ext
     *
     * @return the value of intg_ccp_upload_record.file_ext
     *
     * @mbg.generated
     */
    public String getFileExt() {
        return fileExt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.file_ext
     *
     * @param fileExt the value for intg_ccp_upload_record.file_ext
     *
     * @mbg.generated
     */
    public void setFileExt(String fileExt) {
        this.fileExt = fileExt == null ? null : fileExt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.file_size
     *
     * @return the value of intg_ccp_upload_record.file_size
     *
     * @mbg.generated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.file_size
     *
     * @param fileSize the value for intg_ccp_upload_record.file_size
     *
     * @mbg.generated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.file_stored_path
     *
     * @return the value of intg_ccp_upload_record.file_stored_path
     *
     * @mbg.generated
     */
    public String getFileStoredPath() {
        return fileStoredPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.file_stored_path
     *
     * @param fileStoredPath the value for intg_ccp_upload_record.file_stored_path
     *
     * @mbg.generated
     */
    public void setFileStoredPath(String fileStoredPath) {
        this.fileStoredPath = fileStoredPath == null ? null : fileStoredPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.download_stored_path
     *
     * @return the value of intg_ccp_upload_record.download_stored_path
     *
     * @mbg.generated
     */
    public String getDownloadStoredPath() {
        return downloadStoredPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.download_stored_path
     *
     * @param downloadStoredPath the value for intg_ccp_upload_record.download_stored_path
     *
     * @mbg.generated
     */
    public void setDownloadStoredPath(String downloadStoredPath) {
        this.downloadStoredPath = downloadStoredPath == null ? null : downloadStoredPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.deal_status
     *
     * @return the value of intg_ccp_upload_record.deal_status
     *
     * @mbg.generated
     */
    public Byte getDealStatus() {
        return dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.deal_status
     *
     * @param dealStatus the value for intg_ccp_upload_record.deal_status
     *
     * @mbg.generated
     */
    public void setDealStatus(Byte dealStatus) {
        this.dealStatus = dealStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.created_by
     *
     * @return the value of intg_ccp_upload_record.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.created_by
     *
     * @param createdBy the value for intg_ccp_upload_record.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.created_at
     *
     * @return the value of intg_ccp_upload_record.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.created_at
     *
     * @param createdAt the value for intg_ccp_upload_record.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.updated_by
     *
     * @return the value of intg_ccp_upload_record.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.updated_by
     *
     * @param updatedBy the value for intg_ccp_upload_record.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.updated_at
     *
     * @return the value of intg_ccp_upload_record.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.updated_at
     *
     * @param updatedAt the value for intg_ccp_upload_record.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.is_deleted
     *
     * @return the value of intg_ccp_upload_record.is_deleted
     *
     * @mbg.generated
     */
    public Long getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.is_deleted
     *
     * @param isDeleted the value for intg_ccp_upload_record.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Long isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intg_ccp_upload_record.version
     *
     * @return the value of intg_ccp_upload_record.version
     *
     * @mbg.generated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intg_ccp_upload_record.version
     *
     * @param version the value for intg_ccp_upload_record.version
     *
     * @mbg.generated
     */
    public void setVersion(Long version) {
        this.version = version;
    }
}