package com.utah.frame.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   在线课程基本信息草稿表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table kng_ulcd_draft
 */
public class KngUlcdDraft {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_ulcd_draft.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * Database Column Remarks:
     *   机构Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_ulcd_draft.org_Id
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     * Database Column Remarks:
     *   知识主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_ulcd_draft.kng_Id
     *
     * @mbg.generated
     */
    private String kngId;

    /**
     * Database Column Remarks:
     *   知识草稿版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_ulcd_draft.kng_draft_version
     *
     * @mbg.generated
     */
    private Integer kngDraftVersion;

    /**
     * Database Column Remarks:
     *   创建人Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_ulcd_draft.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     * Database Column Remarks:
     *   创建人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_ulcd_draft.create_fullname
     *
     * @mbg.generated
     */
    private String createFullname;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_ulcd_draft.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_ulcd_draft.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     * Database Column Remarks:
     *   更新人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_ulcd_draft.update_fullname
     *
     * @mbg.generated
     */
    private String updateFullname;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_ulcd_draft.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   在线课程基本信息Json存储
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_ulcd_draft.kng_info_json
     *
     * @mbg.generated
     */
    private String kngInfoJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_ulcd_draft.id
     *
     * @return the value of kng_ulcd_draft.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_ulcd_draft.id
     *
     * @param id the value for kng_ulcd_draft.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_ulcd_draft.org_Id
     *
     * @return the value of kng_ulcd_draft.org_Id
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_ulcd_draft.org_Id
     *
     * @param orgId the value for kng_ulcd_draft.org_Id
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_ulcd_draft.kng_Id
     *
     * @return the value of kng_ulcd_draft.kng_Id
     *
     * @mbg.generated
     */
    public String getKngId() {
        return kngId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_ulcd_draft.kng_Id
     *
     * @param kngId the value for kng_ulcd_draft.kng_Id
     *
     * @mbg.generated
     */
    public void setKngId(String kngId) {
        this.kngId = kngId == null ? null : kngId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_ulcd_draft.kng_draft_version
     *
     * @return the value of kng_ulcd_draft.kng_draft_version
     *
     * @mbg.generated
     */
    public Integer getKngDraftVersion() {
        return kngDraftVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_ulcd_draft.kng_draft_version
     *
     * @param kngDraftVersion the value for kng_ulcd_draft.kng_draft_version
     *
     * @mbg.generated
     */
    public void setKngDraftVersion(Integer kngDraftVersion) {
        this.kngDraftVersion = kngDraftVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_ulcd_draft.create_user_id
     *
     * @return the value of kng_ulcd_draft.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_ulcd_draft.create_user_id
     *
     * @param createUserId the value for kng_ulcd_draft.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_ulcd_draft.create_fullname
     *
     * @return the value of kng_ulcd_draft.create_fullname
     *
     * @mbg.generated
     */
    public String getCreateFullname() {
        return createFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_ulcd_draft.create_fullname
     *
     * @param createFullname the value for kng_ulcd_draft.create_fullname
     *
     * @mbg.generated
     */
    public void setCreateFullname(String createFullname) {
        this.createFullname = createFullname == null ? null : createFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_ulcd_draft.create_time
     *
     * @return the value of kng_ulcd_draft.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_ulcd_draft.create_time
     *
     * @param createTime the value for kng_ulcd_draft.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_ulcd_draft.update_user_id
     *
     * @return the value of kng_ulcd_draft.update_user_id
     *
     * @mbg.generated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_ulcd_draft.update_user_id
     *
     * @param updateUserId the value for kng_ulcd_draft.update_user_id
     *
     * @mbg.generated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_ulcd_draft.update_fullname
     *
     * @return the value of kng_ulcd_draft.update_fullname
     *
     * @mbg.generated
     */
    public String getUpdateFullname() {
        return updateFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_ulcd_draft.update_fullname
     *
     * @param updateFullname the value for kng_ulcd_draft.update_fullname
     *
     * @mbg.generated
     */
    public void setUpdateFullname(String updateFullname) {
        this.updateFullname = updateFullname == null ? null : updateFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_ulcd_draft.update_time
     *
     * @return the value of kng_ulcd_draft.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_ulcd_draft.update_time
     *
     * @param updateTime the value for kng_ulcd_draft.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_ulcd_draft.kng_info_json
     *
     * @return the value of kng_ulcd_draft.kng_info_json
     *
     * @mbg.generated
     */
    public String getKngInfoJson() {
        return kngInfoJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_ulcd_draft.kng_info_json
     *
     * @param kngInfoJson the value for kng_ulcd_draft.kng_info_json
     *
     * @mbg.generated
     */
    public void setKngInfoJson(String kngInfoJson) {
        this.kngInfoJson = kngInfoJson == null ? null : kngInfoJson.trim();
    }
}