package com.utah.frame.entity;

import java.util.Date;

public class KngUserStudyExt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_user_study_ext.id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_user_study_ext.org_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_user_study_ext.kng_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    private String kngId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_user_study_ext.user_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_user_study_ext.pop_up
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    private Byte popUp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_user_study_ext.create_user_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    private String createUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_user_study_ext.create_fullname
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    private String createFullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_user_study_ext.create_time
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_user_study_ext.update_user_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    private String updateUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_user_study_ext.update_fullname
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    private String updateFullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_user_study_ext.update_time
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_user_study_ext.id
     *
     * @return the value of kng_user_study_ext.id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_user_study_ext.id
     *
     * @param id the value for kng_user_study_ext.id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_user_study_ext.org_id
     *
     * @return the value of kng_user_study_ext.org_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_user_study_ext.org_id
     *
     * @param orgId the value for kng_user_study_ext.org_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_user_study_ext.kng_id
     *
     * @return the value of kng_user_study_ext.kng_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public String getKngId() {
        return kngId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_user_study_ext.kng_id
     *
     * @param kngId the value for kng_user_study_ext.kng_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public void setKngId(String kngId) {
        this.kngId = kngId == null ? null : kngId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_user_study_ext.user_id
     *
     * @return the value of kng_user_study_ext.user_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_user_study_ext.user_id
     *
     * @param userId the value for kng_user_study_ext.user_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_user_study_ext.pop_up
     *
     * @return the value of kng_user_study_ext.pop_up
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public Byte getPopUp() {
        return popUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_user_study_ext.pop_up
     *
     * @param popUp the value for kng_user_study_ext.pop_up
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public void setPopUp(Byte popUp) {
        this.popUp = popUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_user_study_ext.create_user_id
     *
     * @return the value of kng_user_study_ext.create_user_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_user_study_ext.create_user_id
     *
     * @param createUserId the value for kng_user_study_ext.create_user_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_user_study_ext.create_fullname
     *
     * @return the value of kng_user_study_ext.create_fullname
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public String getCreateFullname() {
        return createFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_user_study_ext.create_fullname
     *
     * @param createFullname the value for kng_user_study_ext.create_fullname
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public void setCreateFullname(String createFullname) {
        this.createFullname = createFullname == null ? null : createFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_user_study_ext.create_time
     *
     * @return the value of kng_user_study_ext.create_time
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_user_study_ext.create_time
     *
     * @param createTime the value for kng_user_study_ext.create_time
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_user_study_ext.update_user_id
     *
     * @return the value of kng_user_study_ext.update_user_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_user_study_ext.update_user_id
     *
     * @param updateUserId the value for kng_user_study_ext.update_user_id
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_user_study_ext.update_fullname
     *
     * @return the value of kng_user_study_ext.update_fullname
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public String getUpdateFullname() {
        return updateFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_user_study_ext.update_fullname
     *
     * @param updateFullname the value for kng_user_study_ext.update_fullname
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public void setUpdateFullname(String updateFullname) {
        this.updateFullname = updateFullname == null ? null : updateFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_user_study_ext.update_time
     *
     * @return the value of kng_user_study_ext.update_time
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_user_study_ext.update_time
     *
     * @param updateTime the value for kng_user_study_ext.update_time
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}