package com.utah.frame.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   在线课程重新上传表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table kng_knowledge_reupload
 */
public class KnowledgeReupload {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_knowledge_reupload.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   组织id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_knowledge_reupload.org_id
     *
     * @mbg.generated
     */
    private String orgId;

    /**
     * Database Column Remarks:
     *   知识id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_knowledge_reupload.kng_id
     *
     * @mbg.generated
     */
    private String kngId;

    /**
     * Database Column Remarks:
     *   文件id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_knowledge_reupload.file_id
     *
     * @mbg.generated
     */
    private String fileId;

    /**
     * Database Column Remarks:
     *   创建人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_knowledge_reupload.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_knowledge_reupload.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_knowledge_reupload.update_user_id
     *
     * @mbg.generated
     */
    private String updateUserId;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kng_knowledge_reupload.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_knowledge_reupload.id
     *
     * @return the value of kng_knowledge_reupload.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_knowledge_reupload.id
     *
     * @param id the value for kng_knowledge_reupload.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_knowledge_reupload.org_id
     *
     * @return the value of kng_knowledge_reupload.org_id
     *
     * @mbg.generated
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_knowledge_reupload.org_id
     *
     * @param orgId the value for kng_knowledge_reupload.org_id
     *
     * @mbg.generated
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_knowledge_reupload.kng_id
     *
     * @return the value of kng_knowledge_reupload.kng_id
     *
     * @mbg.generated
     */
    public String getKngId() {
        return kngId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_knowledge_reupload.kng_id
     *
     * @param kngId the value for kng_knowledge_reupload.kng_id
     *
     * @mbg.generated
     */
    public void setKngId(String kngId) {
        this.kngId = kngId == null ? null : kngId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_knowledge_reupload.file_id
     *
     * @return the value of kng_knowledge_reupload.file_id
     *
     * @mbg.generated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_knowledge_reupload.file_id
     *
     * @param fileId the value for kng_knowledge_reupload.file_id
     *
     * @mbg.generated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_knowledge_reupload.create_user_id
     *
     * @return the value of kng_knowledge_reupload.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_knowledge_reupload.create_user_id
     *
     * @param createUserId the value for kng_knowledge_reupload.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_knowledge_reupload.create_time
     *
     * @return the value of kng_knowledge_reupload.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_knowledge_reupload.create_time
     *
     * @param createTime the value for kng_knowledge_reupload.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_knowledge_reupload.update_user_id
     *
     * @return the value of kng_knowledge_reupload.update_user_id
     *
     * @mbg.generated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_knowledge_reupload.update_user_id
     *
     * @param updateUserId the value for kng_knowledge_reupload.update_user_id
     *
     * @mbg.generated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kng_knowledge_reupload.update_time
     *
     * @return the value of kng_knowledge_reupload.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kng_knowledge_reupload.update_time
     *
     * @param updateTime the value for kng_knowledge_reupload.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}