package com.utah.frame.mapper;

import com.utah.frame.entity.IntgCcpUploadRecord;

public interface IntgCcpUploadRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_ccp_upload_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_ccp_upload_record
     *
     * @mbg.generated
     */
    int insert(IntgCcpUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_ccp_upload_record
     *
     * @mbg.generated
     */
    int insertSelective(IntgCcpUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_ccp_upload_record
     *
     * @mbg.generated
     */
    IntgCcpUploadRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_ccp_upload_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IntgCcpUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_ccp_upload_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IntgCcpUploadRecord record);
}