package com.utah.frame.mapper;

import com.utah.frame.entity.IntgProjectLine;

public interface IntgProjectLineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line
     *
     * @mbg.generated
     */
    int insert(IntgProjectLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line
     *
     * @mbg.generated
     */
    int insertSelective(IntgProjectLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line
     *
     * @mbg.generated
     */
    IntgProjectLine selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IntgProjectLine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IntgProjectLine record);
}