package com.utah.frame.mapper;

import com.utah.frame.entity.IntgProjectLineMetadata;

public interface IntgProjectLineMetadataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line_metadata
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line_metadata
     *
     * @mbg.generated
     */
    int insert(IntgProjectLineMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line_metadata
     *
     * @mbg.generated
     */
    int insertSelective(IntgProjectLineMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line_metadata
     *
     * @mbg.generated
     */
    IntgProjectLineMetadata selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line_metadata
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IntgProjectLineMetadata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intg_settlement_line_metadata
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IntgProjectLineMetadata record);
}