package com.utah.frame.mapper;

import com.utah.frame.entity.KngUserViewRecord;

public interface KngUserViewRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_view_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_view_record
     *
     * @mbg.generated
     */
    int insert(KngUserViewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_view_record
     *
     * @mbg.generated
     */
    int insertSelective(KngUserViewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_view_record
     *
     * @mbg.generated
     */
    KngUserViewRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_view_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KngUserViewRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_view_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KngUserViewRecord record);
}