package com.utah.frame.mapper;

import com.utah.frame.entity.KngUserStudyExt;

public interface KngUserStudyExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_study_ext
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_study_ext
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    int insert(KngUserStudyExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_study_ext
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    int insertSelective(KngUserStudyExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_study_ext
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    KngUserStudyExt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_study_ext
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    int updateByPrimaryKeySelective(KngUserStudyExt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_user_study_ext
     *
     * @mbg.generated Tue Nov 10 15:22:12 CST 2020
     */
    int updateByPrimaryKey(KngUserStudyExt record);
}