package com.utah.frame.mapper;

import com.utah.frame.entity.KngUlcdDraft;

public interface KngUlcdDraftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_ulcd_draft
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_ulcd_draft
     *
     * @mbg.generated
     */
    int insert(KngUlcdDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_ulcd_draft
     *
     * @mbg.generated
     */
    int insertSelective(KngUlcdDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_ulcd_draft
     *
     * @mbg.generated
     */
    KngUlcdDraft selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_ulcd_draft
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KngUlcdDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_ulcd_draft
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(KngUlcdDraft record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_ulcd_draft
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KngUlcdDraft record);
}