package com.utah.frame.mapper;

import com.utah.frame.entity.KnowledgeReupload;

public interface KnowledgeReuploadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_knowledge_reupload
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_knowledge_reupload
     *
     * @mbg.generated
     */
    int insert(KnowledgeReupload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_knowledge_reupload
     *
     * @mbg.generated
     */
    int insertSelective(KnowledgeReupload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_knowledge_reupload
     *
     * @mbg.generated
     */
    KnowledgeReupload selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_knowledge_reupload
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KnowledgeReupload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kng_knowledge_reupload
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KnowledgeReupload record);
}